### ISSUE TITLE
Error Message "対応していません"

### ISSUE THREAD

**Issue by Explorare** [himananiito/livedl#56]
[ENV]
Windows 10 22H2
livedl2 a0.1

```
@explo ➜ livedl2 .\livedl2.exe
open action-track-id.txt: The system cannot find the file specified.
{"meta":{"status":201},"data":"wiXcbG5dv1_1672710433115"}
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (3):
        - index.html
        - template1.html
        -

[GIN-debug] GET    /                         --> main.main.func5 (1 handlers)
[GIN-debug] POST   /register                 --> main.main.func6 (1 handlers)
[GIN-debug] POST   /close                    --> main.main.func7 (1 handlers)
[GIN-debug] GET    /get-list                 --> main.main.func8 (1 handlers)
[GIN-debug] POST   /nico-finder              --> main.main.func9 (1 handlers)
[GIN-debug] GET    /pprof/:name              --> main.main.func10 (1 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] Listening and serving HTTP on :8080

main.register{Target:"lv338385557", NicocasArchive:true, StartPositionEn:false, StartPosition:0, ArchiveWait:2}
lv338385557
対応していません:https://live.nicovideo.jp/watch/lv338385557
```

So the parser doesn't the new site?

**Comment by nnn-revo2012** [comment]
Hi,
livedl2 has not been updated since 2019.
Build and use livedl, or use 'ニコ生新配信録画ツール（仮' or streamlink.
(ニコ生新配信録画ツール（仮 is only Windows and Japanese)

**Comment by nnn-revo2012** [comment]
I write in Japanese because it's troublesome,
Even though livedl2 has not been maintained since 2019, the fact that the error comes out now means that you can pass the expiration date and correct the WebSocket sequence at the time of login, that is, do you have development skills & environment?
In that case, I think you should delete the whole part that sends tracking with livedl2.
Personally, I think it's better to build and use livedl instead of doing that.

めんどくさいから日本語で書くけど、
livedl2って2019からメンテされてないにもかかわらず今そのエラー出るってことは使用期限をパスしたりログイン時のWebSocketのシーケンスを修正できる、つまり開発スキル＆環境があるんでしょうか？
なら、livedl2でtrackingを送ってる部分をまるまる削除すればいいと思います。
個人的にはそれをするぐらいならlivedlをビルドして使った方がよっぽどよいかと思います。
